from __future__ import annotations

import copy
import re
from typing import Any


def fragrance(
    brand: str,
    name: str,
    collection_type: str,
    gender: str,
    family: str,
    retail_price_inr: int,
    bottle_size_ml: int,
    top_notes: list[str],
    heart_notes: list[str],
    base_notes: list[str],
    signature: str,
    colors: tuple[str, str],
    *,
    concentration: str = "Eau de Parfum",
    origin: str = "France",
    featured: bool = False,
    sale_plan: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "brand": brand,
        "name": name,
        "collection_type": collection_type,
        "gender": gender,
        "family": family,
        "retail_price_inr": retail_price_inr,
        "bottle_size_ml": bottle_size_ml,
        "top_notes": top_notes,
        "heart_notes": heart_notes,
        "base_notes": base_notes,
        "signature": signature,
        "colors": colors,
        "concentration": concentration,
        "origin": origin,
        "featured": featured,
        "sale_plan": sale_plan or {},
    }


SIGNATURE_NICHE = {
    "retail_stock": 4,
    "tester": True,
    "tester_stock": 2,
    "partial": True,
    "partial_fill_ml": 38,
    "partial_multiplier": 0.84,
    "decant_factor": 1.08,
}

ULTRA_LUXE = {
    "retail_stock": 2,
    "tester": False,
    "partial": True,
    "partial_fill_ml": 32,
    "partial_multiplier": 0.9,
    "decant_factor": 1.18,
}

MODERN_NICHE = {
    "retail_stock": 5,
    "tester": True,
    "tester_stock": 2,
    "partial": True,
    "partial_fill_ml": 40,
    "partial_multiplier": 0.82,
    "decant_factor": 1.02,
}

DESIGNER = {
    "retail_stock": 7,
    "tester": True,
    "tester_stock": 3,
    "partial": False,
    "decant_factor": 0.9,
}

DESIGNER_INTENSE = {
    "retail_stock": 6,
    "tester": True,
    "tester_stock": 2,
    "partial": True,
    "partial_fill_ml": 35,
    "partial_multiplier": 0.8,
    "decant_factor": 0.94,
}


BASE_FRAGRANCES = [
    fragrance(
        "Creed",
        "Aventus",
        "niche",
        "him",
        "woody fruity",
        28950,
        100,
        ["Pineapple", "Bergamot", "Blackcurrant"],
        ["Birch", "Patchouli", "Jasmine"],
        ["Oakmoss", "Musk", "Ambergris"],
        "A boardroom icon with bright fruit, smoky woods, and polished masculinity.",
        ("#d4b273", "#2f2823"),
        featured=True,
        sale_plan=SIGNATURE_NICHE,
    ),
    fragrance(
        "Creed",
        "Green Irish Tweed",
        "niche",
        "him",
        "green aromatic",
        27250,
        100,
        ["Lemon Verbena", "Peppermint"],
        ["Violet Leaf", "Iris"],
        ["Sandalwood", "Ambergris"],
        "Clean tailoring in fragrance form with vivid green freshness and suave woods.",
        ("#6f845c", "#202a22"),
        sale_plan=SIGNATURE_NICHE,
    ),
    fragrance(
        "Creed",
        "Silver Mountain Water",
        "niche",
        "unisex",
        "musky citrus",
        26850,
        100,
        ["Bergamot", "Mandarin"],
        ["Green Tea", "Blackcurrant"],
        ["Musk", "Petitgrain", "Sandalwood"],
        "An airy alpine citrus with metallic freshness and smooth tea musk.",
        ("#d7e7f0", "#4e6674"),
        sale_plan=SIGNATURE_NICHE,
    ),
    fragrance(
        "Amouage",
        "Interlude Man",
        "niche",
        "him",
        "amber smoky",
        26500,
        100,
        ["Oregano", "Pimento Berry", "Bergamot"],
        ["Incense", "Amber", "Labdanum"],
        ["Leather", "Oud", "Patchouli"],
        "A dramatic incense-and-amber storm that wears like black velvet armor.",
        ("#a56b4d", "#261815"),
        featured=True,
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Amouage",
        "Reflection Man",
        "niche",
        "him",
        "white floral woody",
        24800,
        100,
        ["Rosemary", "Pink Pepper", "Petitgrain"],
        ["Jasmine", "Neroli", "Orris"],
        ["Sandalwood", "Vetiver", "Cedarwood"],
        "Sharp tailoring wrapped in neroli, orris, and creamy woods.",
        ("#ded3bb", "#4f3d28"),
        sale_plan=MODERN_NICHE,
    ),
    fragrance(
        "Amouage",
        "Guidance",
        "niche",
        "her",
        "fruity amber",
        29850,
        100,
        ["Pear", "Hazelnut", "Frankincense"],
        ["Osmanthus", "Rose Sambac", "Saffron"],
        ["Sandalwood", "Akigalawood", "Ambergris"],
        "Luminous pear and saffron drifting into plush sandalwood and amber.",
        ("#c87d6f", "#5f2941"),
        featured=True,
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Kilian",
        "Angels' Share",
        "niche",
        "unisex",
        "boozy gourmand",
        22850,
        50,
        ["Cognac", "Cinnamon"],
        ["Tonka Bean", "Oak", "Hedione"],
        ["Praline", "Vanilla", "Sandalwood"],
        "Warm cognac, cinnamon, and praline with huge after-hours charisma.",
        ("#c5823f", "#432718"),
        featured=True,
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Kilian",
        "Black Phantom",
        "niche",
        "unisex",
        "coffee gourmand",
        24150,
        50,
        ["Rum", "Sugar Cane"],
        ["Dark Chocolate", "Coffee"],
        ["Caramel", "Vetiver", "Cyanide Accord"],
        "Dark coffee, rum, and caramel turned into an unapologetically rich signature.",
        ("#8e5f47", "#191311"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Kilian",
        "Love Don't Be Shy",
        "niche",
        "her",
        "floral gourmand",
        23250,
        50,
        ["Neroli", "Bergamot", "Pink Pepper"],
        ["Orange Blossom", "Honeysuckle", "Jasmine"],
        ["Marshmallow", "Vanilla", "Musk"],
        "Orange blossom and marshmallow served with glamorous sweetness.",
        ("#efbaae", "#6f4047"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Clive Christian",
        "X Masculine",
        "niche",
        "him",
        "amber spicy",
        39500,
        50,
        ["Rhubarb", "Pineapple", "Bergamot"],
        ["Paprika", "Iris", "Jasmine"],
        ["Cinnamon", "Oakmoss", "Vetiver"],
        "Royal-level richness balancing fruit, spice, and mossy warmth.",
        ("#d9b169", "#47341d"),
        featured=True,
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Clive Christian",
        "X Feminine",
        "niche",
        "her",
        "chypre fruity",
        39500,
        50,
        ["Peach", "Rhubarb", "Bergamot"],
        ["Rose", "Jasmine", "Tuberose"],
        ["Patchouli", "Vanilla", "Vetiver"],
        "A decadent peach-and-rose chypre with couture-level volume.",
        ("#d0a1ae", "#5a3142"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Clive Christian",
        "1872 Masculine",
        "niche",
        "him",
        "citrus woody",
        36500,
        50,
        ["Citrus Accord", "Lavender", "Pepper"],
        ["Clary Sage", "Nutmeg", "Tagete"],
        ["Cedarwood", "Frankincense", "Musk"],
        "An aristocratic citrus opening that settles into refined woods and spice.",
        ("#d1c37b", "#30402b"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Roja",
        "Elysium Pour Homme",
        "niche",
        "him",
        "citrus aromatic",
        31500,
        100,
        ["Grapefruit", "Lime", "Bergamot"],
        ["Juniper Berry", "Blackcurrant", "Apple"],
        ["Vetiver", "Ambergris", "Leather"],
        "A sparkling blue-chypre profile that feels expensive from the first spray.",
        ("#93d1d7", "#204d5b"),
        featured=True,
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Roja",
        "Enigma Pour Homme",
        "niche",
        "him",
        "amber cognac",
        34250,
        100,
        ["Bergamot", "Neroli"],
        ["Cognac", "Heliotrope", "Jasmine"],
        ["Tobacco", "Vanilla", "Patchouli"],
        "Cognac, tobacco, and vanilla blended into a plush late-night signature.",
        ("#c08b56", "#2b1a16"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Roja",
        "Burlington 1819",
        "niche",
        "unisex",
        "citrus leather",
        31850,
        100,
        ["Grapefruit", "Lime", "Mint"],
        ["Rum", "Ginger", "Cinnamon"],
        ["Patchouli", "Cashmere Wood", "Ambergris"],
        "Bright citrus collides with rum and leather for a jet-set profile.",
        ("#f0c888", "#5a3323"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Xerjoff",
        "Naxos",
        "niche",
        "unisex",
        "honey tobacco",
        21650,
        100,
        ["Lavender", "Bergamot", "Lemon"],
        ["Honey", "Jasmine Sambac", "Cinnamon"],
        ["Tobacco Leaf", "Tonka Bean", "Vanilla"],
        "One of the most loved tobacco-honey fragrances in the niche world.",
        ("#d4a96b", "#4c2e20"),
        featured=True,
        sale_plan=SIGNATURE_NICHE,
    ),
    fragrance(
        "Xerjoff",
        "Erba Pura",
        "niche",
        "unisex",
        "fruity musky",
        19850,
        100,
        ["Orange", "Lemon", "Bergamot"],
        ["Mediterranean Fruits"],
        ["White Musk", "Amber", "Vanilla"],
        "An explosive fruit basket over silky musk with huge trail.",
        ("#f5b24c", "#7a3768"),
        sale_plan=MODERN_NICHE,
    ),
    fragrance(
        "Xerjoff",
        "Alexandria II",
        "niche",
        "unisex",
        "oud woody",
        31250,
        100,
        ["Rosewood", "Lavender", "Cinnamon"],
        ["Cedarwood", "Lily of the Valley", "Rose"],
        ["Oud", "Amber", "Vanilla"],
        "A majestic oud composition with polished florals and smooth sweetness.",
        ("#9a7d58", "#2e1c14"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Parfums de Marly",
        "Layton",
        "niche",
        "him",
        "amber vanilla",
        22800,
        75,
        ["Apple", "Lavender", "Mandarin"],
        ["Geranium", "Violet", "Jasmine"],
        ["Vanilla", "Cardamom", "Guaiac Wood"],
        "A plush apple-vanilla crowd favorite with rich masculine lift.",
        ("#b08b66", "#1f1a1e"),
        featured=True,
        sale_plan=MODERN_NICHE,
    ),
    fragrance(
        "Parfums de Marly",
        "Delina",
        "niche",
        "her",
        "floral fruity",
        24500,
        75,
        ["Rhubarb", "Lychee", "Bergamot"],
        ["Turkish Rose", "Peony", "Vanilla"],
        ["Cashmeran", "Musk", "Incense"],
        "A sparkling lychee-rose icon that feels airy and glamorous.",
        ("#e8a7b5", "#7c3f5d"),
        featured=True,
        sale_plan=MODERN_NICHE,
    ),
    fragrance(
        "Parfums de Marly",
        "Haltane",
        "niche",
        "him",
        "woody aromatic",
        25650,
        125,
        ["Clary Sage", "Lavender", "Bergamot"],
        ["Praline", "Saffron", "Cedarwood"],
        ["Oud", "Patchouli", "Musk"],
        "A modern green-oud profile with sweetness, polish, and major presence.",
        ("#7f8563", "#241f1c"),
        sale_plan=MODERN_NICHE,
    ),
    fragrance(
        "Maison Francis Kurkdjian",
        "Baccarat Rouge 540",
        "niche",
        "unisex",
        "amber floral",
        25950,
        70,
        ["Saffron", "Jasmine"],
        ["Amberwood", "Ambergris"],
        ["Fir Resin", "Cedarwood"],
        "Radiant saffroned amberwood that projects with crystalline luxury.",
        ("#e9c48f", "#8d3a35"),
        featured=True,
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Maison Francis Kurkdjian",
        "Grand Soir",
        "niche",
        "unisex",
        "amber vanilla",
        24250,
        70,
        ["Spanish Labdanum"],
        ["Benzoin", "Lavender"],
        ["Vanilla", "Tonka Bean", "Amber"],
        "A molten amber-vanilla evening fragrance with impeccable smoothness.",
        ("#b58a4b", "#341d1a"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Maison Francis Kurkdjian",
        "Oud Satin Mood",
        "niche",
        "unisex",
        "oud rose",
        27950,
        70,
        ["Violet Accord"],
        ["Rose", "Turkish Rose"],
        ["Oud", "Vanilla", "Benzoin"],
        "Velvet rose and oud wrapped in sweet resinous softness.",
        ("#cc90a9", "#4a253b"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Chanel",
        "Bleu de Chanel Parfum",
        "designer",
        "him",
        "woody aromatic",
        13950,
        100,
        ["Lemon Zest", "Bergamot", "Mint"],
        ["Lavender", "Geranium", "Pineapple"],
        ["Sandalwood", "Cedar", "Tonka Bean"],
        "Ultra versatile blue luxury with creamy woods and polished freshness.",
        ("#4e6d85", "#171f2a"),
        featured=True,
        sale_plan=DESIGNER_INTENSE,
    ),
    fragrance(
        "Chanel",
        "Coco Mademoiselle",
        "designer",
        "her",
        "amber citrus",
        14750,
        100,
        ["Orange", "Mandarin", "Bergamot"],
        ["Rose", "Jasmine", "Ylang-Ylang"],
        ["Patchouli", "Vanilla", "White Musk"],
        "A timeless dressy citrus-patchouli feminine with Parisian sparkle.",
        ("#efc7b1", "#764f4c"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Chanel",
        "Chance Eau Tendre",
        "designer",
        "her",
        "floral fruity",
        13250,
        100,
        ["Grapefruit", "Quince"],
        ["Jasmine", "Hyacinth"],
        ["White Musk", "Iris", "Amber"],
        "Delicate fruit and airy florals for an elegant everyday signature.",
        ("#f4d1cf", "#9f7187"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Gucci",
        "Gucci Guilty Pour Homme",
        "designer",
        "him",
        "aromatic spicy",
        9950,
        90,
        ["Lavender", "Lemon"],
        ["Orange Blossom", "Coriander"],
        ["Patchouli", "Cedarwood"],
        "Clean aromatic spice with smooth woods and nightlife energy.",
        ("#b8b1a6", "#33312d"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Gucci",
        "Bloom Eau de Parfum",
        "designer",
        "her",
        "white floral",
        11250,
        100,
        ["Jasmine Bud"],
        ["Tuberose", "Rangoon Creeper"],
        ["Musk", "Sandalwood"],
        "A lush white-floral bouquet with soft naturalistic lift.",
        ("#f0c6c9", "#5b434b"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Gucci",
        "Flora Gorgeous Gardenia",
        "designer",
        "her",
        "floral sweet",
        11850,
        100,
        ["Pear Blossom", "Red Berries", "Italian Mandarin"],
        ["Gardenia", "Jasmine", "Frangipani"],
        ["Brown Sugar", "Patchouli"],
        "Bright berries and creamy florals softened by sugared warmth.",
        ("#f4abc0", "#7b4d59"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Dior",
        "Sauvage Elixir",
        "designer",
        "him",
        "aromatic amber",
        14950,
        60,
        ["Grapefruit", "Nutmeg", "Cinnamon"],
        ["Lavender"],
        ["Licorice", "Sandalwood", "Amber"],
        "Dense, spicy, and assertive with massive longevity and trail.",
        ("#6f8190", "#171e27"),
        featured=True,
        sale_plan=DESIGNER_INTENSE,
    ),
    fragrance(
        "Dior",
        "Dior Homme Intense",
        "designer",
        "him",
        "iris woody",
        12650,
        100,
        ["Lavender"],
        ["Iris", "Ambrette", "Pear"],
        ["Vetiver", "Virginia Cedar"],
        "A polished iris-cacao menswear classic with a velvety finish.",
        ("#b1a89b", "#352c29"),
        sale_plan=DESIGNER_INTENSE,
    ),
    fragrance(
        "Dior",
        "J'adore Eau de Parfum",
        "designer",
        "her",
        "floral fruity",
        13950,
        100,
        ["Pear", "Melon", "Magnolia"],
        ["Jasmine", "Rose", "Lily of the Valley"],
        ["Vanilla", "Musk", "Cedarwood"],
        "A gleaming bouquet that feels golden, feminine, and unmistakably classic.",
        ("#e8c478", "#7a5730"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Yves Saint Laurent",
        "Y Eau de Parfum",
        "designer",
        "him",
        "aromatic woody",
        11250,
        100,
        ["Apple", "Ginger", "Bergamot"],
        ["Sage", "Juniper Berries", "Geranium"],
        ["Tonka Bean", "Amberwood", "Cedar"],
        "A sharp modern office-to-evening blue fragrance with real punch.",
        ("#7da4c2", "#1f3042"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Yves Saint Laurent",
        "Libre Intense",
        "designer",
        "her",
        "amber floral",
        12650,
        90,
        ["Mandarin", "Lavender", "Bergamot"],
        ["Orange Blossom", "Jasmine Sambac"],
        ["Vanilla", "Tonka Bean", "Ambergris"],
        "Bold lavender-orange blossom femininity with a creamy ambery core.",
        ("#e2a88b", "#57354a"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Yves Saint Laurent",
        "Black Opium",
        "designer",
        "her",
        "coffee vanilla",
        11850,
        90,
        ["Pear", "Pink Pepper", "Orange Blossom"],
        ["Coffee", "Jasmine", "Licorice"],
        ["Vanilla", "Patchouli", "Cedarwood"],
        "Night-out sweetness with coffee depth and a glossy feminine finish.",
        ("#d39b92", "#24171f"),
        sale_plan=DESIGNER_INTENSE,
    ),
    fragrance(
        "Giorgio Armani",
        "Acqua di Gio Profondo",
        "designer",
        "him",
        "marine aromatic",
        10950,
        100,
        ["Green Mandarin", "Bergamot", "Aquozone"],
        ["Rosemary", "Lavender", "Cypress"],
        ["Mineral Amber", "Musk", "Patchouli"],
        "Oceanic freshness sharpened with herbs and mineral amber depth.",
        ("#4ea1c3", "#143241"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Giorgio Armani",
        "Stronger With You Intensely",
        "designer",
        "him",
        "amber gourmand",
        10650,
        100,
        ["Pink Pepper", "Juniper", "Violet"],
        ["Toffee", "Cinnamon", "Lavender"],
        ["Amber", "Tonka Bean", "Suede"],
        "A sweet-spicy amber powerhouse built for evenings and colder weather.",
        ("#b18057", "#2f211d"),
        sale_plan=DESIGNER_INTENSE,
    ),
    fragrance(
        "Giorgio Armani",
        "Si Passione",
        "designer",
        "her",
        "fruity floral",
        11850,
        100,
        ["Pear", "Pink Pepper", "Blackcurrant"],
        ["Rose", "Jasmine", "Heliotrope"],
        ["Vanilla", "Cedarwood", "Patchouli"],
        "A polished red-fruit floral with soft vanilla confidence.",
        ("#c24f59", "#49212a"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Prada",
        "Luna Rossa Black",
        "designer",
        "him",
        "amber musk",
        9950,
        100,
        ["Bergamot", "Angelica"],
        ["Patchouli", "Coumarin"],
        ["Musk", "Amber", "Sandalwood"],
        "Smooth, dark, and powdery with a luxe urban evening feel.",
        ("#6b6771", "#161417"),
        sale_plan=DESIGNER_INTENSE,
    ),
    fragrance(
        "Prada",
        "Paradoxe",
        "designer",
        "her",
        "amber floral",
        12950,
        90,
        ["Pear", "Mandarin", "Calabrian Bergamot"],
        ["Orange Blossom", "Neroli", "Jasmine Sambac"],
        ["Amber", "White Musk", "Benzoin"],
        "Modern clean florals lifted with radiant amber and soft musk.",
        ("#efc2b8", "#68515b"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Prada",
        "L'Homme Prada",
        "designer",
        "him",
        "powdery woody",
        10950,
        100,
        ["Neroli", "Black Pepper", "Cardamom"],
        ["Iris", "Violet", "Geranium"],
        ["Amber", "Patchouli", "Cedarwood"],
        "Soap-clean iris tailored for understated luxury and office wear.",
        ("#b4b9c5", "#28303b"),
        sale_plan=DESIGNER,
    ),
    fragrance(
        "Tom Ford",
        "Oud Wood",
        "designer",
        "unisex",
        "woody spicy",
        23850,
        50,
        ["Cardamom", "Pepper", "Rosewood"],
        ["Oud", "Sandalwood", "Vetiver"],
        ["Tonka Bean", "Amber", "Vanilla"],
        "Smooth accessible oud framed by cardamom and velvety woods.",
        ("#a2805b", "#2e1f17"),
        featured=True,
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Tom Ford",
        "Tobacco Vanille",
        "designer",
        "unisex",
        "tobacco vanilla",
        25500,
        50,
        ["Tobacco Leaf", "Spices"],
        ["Vanilla", "Cacao", "Tonka Bean"],
        ["Dried Fruits", "Wood Sap"],
        "Dense tobacco and vanilla with plush warmth and lounge-room luxury.",
        ("#b07c48", "#291813"),
        sale_plan=ULTRA_LUXE,
    ),
    fragrance(
        "Tom Ford",
        "Lost Cherry",
        "designer",
        "unisex",
        "fruity amber",
        26500,
        50,
        ["Black Cherry", "Bitter Almond", "Liquor"],
        ["Turkish Rose", "Jasmine Sambac", "Plum"],
        ["Tonka Bean", "Vanilla", "Peru Balsam"],
        "Liquored cherry and almond that turns rich, sweet, and seductive.",
        ("#b04953", "#2a1217"),
        sale_plan=ULTRA_LUXE,
    ),
]


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def round_to_50(value: float) -> int:
    return int(round(value / 50.0) * 50)


def money_band(price_inr: int) -> str:
    if price_inr >= 30000:
        return "collector"
    if price_inr >= 20000:
        return "haute"
    if price_inr >= 12000:
        return "signature"
    return "daily-luxury"


def decant_price(retail_price_inr: int, size_ml: int, factor: float) -> int:
    base = {
        5: max(950, retail_price_inr * 0.07),
        10: max(1750, retail_price_inr * 0.13),
        20: max(3250, retail_price_inr * 0.24),
        30: max(4650, retail_price_inr * 0.34),
    }[size_ml]
    return round_to_50(base * factor)


def clone_sale_plan(base_plan: dict[str, Any] | None) -> dict[str, Any]:
    return copy.deepcopy(base_plan or {})


def build_variants(item: dict[str, Any]) -> list[dict[str, Any]]:
    plan = clone_sale_plan(item.get("sale_plan"))
    bottle_size_ml = item["bottle_size_ml"]
    retail_price = item["retail_price_inr"]
    slug = item["slug"]
    band = money_band(retail_price)

    variants = []
    retail_stock = int(plan.get("retail_stock", 4))
    variants.append(
        {
            "sku": f"{slug}-retail-{bottle_size_ml}",
            "sale_type": "retail",
            "size_label": f"{bottle_size_ml}ml Retail Bottle",
            "size_ml": bottle_size_ml,
            "price_inr": retail_price,
            "stock_units": retail_stock,
            "badge": "Signature Bottle" if item["featured"] else band.title(),
            "statement": "Factory-sealed retail presentation with full packaging.",
        }
    )

    if plan.get("tester"):
        tester_price = round_to_50(retail_price * 0.88)
        variants.append(
            {
                "sku": f"{slug}-tester-{bottle_size_ml}",
                "sale_type": "tester",
                "size_label": f"{bottle_size_ml}ml Tester",
                "size_ml": bottle_size_ml,
                "price_inr": tester_price,
                "stock_units": int(plan.get("tester_stock", 2)),
                "badge": "Value Pick",
                "statement": "Original juice in tester format, ideal for regular wearers.",
            }
        )

    factor = float(plan.get("decant_factor", 1.0))
    for size_ml, stock_units in ((5, 12), (10, 10), (20, 6), (30, 4)):
        if size_ml >= bottle_size_ml:
            continue
        if size_ml == 30 and bottle_size_ml < 70:
            continue
        variants.append(
            {
                "sku": f"{slug}-decant-{size_ml}",
                "sale_type": "decant",
                "size_label": f"{size_ml}ml Decant",
                "size_ml": size_ml,
                "price_inr": decant_price(retail_price, size_ml, factor),
                "stock_units": stock_units,
                "badge": "Best for Discovery" if size_ml == 10 else "Decant",
                "statement": "Hand-filled in travel atomizers for easy sampling and rotation.",
            }
        )

    if plan.get("partial"):
        fill_ml = int(plan.get("partial_fill_ml", max(25, bottle_size_ml // 2)))
        partial_price = round_to_50(
            retail_price
            * (fill_ml / bottle_size_ml)
            * float(plan.get("partial_multiplier", 0.82))
        )
        variants.append(
            {
                "sku": f"{slug}-partial-{fill_ml}",
                "sale_type": "partial",
                "size_label": f"Partial Bottle - {fill_ml}ml left",
                "size_ml": fill_ml,
                "price_inr": partial_price,
                "stock_units": 1,
                "badge": "Collector Access",
                "statement": "Original bottle with remaining fill level clearly disclosed.",
            }
        )

    return variants


def build_catalog_seed() -> list[dict[str, Any]]:
    catalog = []
    seen_slugs = set()

    for index, item in enumerate(BASE_FRAGRANCES):
        slug_root = slugify(f"{item['brand']}-{item['name']}")
        slug = slug_root
        suffix = 2
        while slug in seen_slugs:
            slug = f"{slug_root}-{suffix}"
            suffix += 1

        seen_slugs.add(slug)
        record = dict(item)
        record["slug"] = slug
        record["rank"] = index + 1
        record["variants"] = build_variants(record)
        record["artwork_kind"] = "generated"
        record["image_url"] = f"/artwork/{slug}.svg"
        catalog.append(record)

    return catalog
